#include "unit.h"

namespace Unit {
bool is_worker(UnitName u) {
    return u == Terran_SCV;
}

bool is_gas(UnitName u) {
    return u == Terran_Refinery;
}

bool is_addon(UnitName u) {
    return (u >= Terran_Machine_Shop && u <= Terran_Covert_Ops);
}

bool req_addon(UnitName u) {
    return ((u == Terran_Siege_Tank)
            || (u >= Terran_Dropship && u <= Terran_Battlecruiser));
}

bool is_upgrade(UnitName u) {
    return (u >= Terran_U238_Shells && u <= Terran_Ship_Plating_3);
}

namespace {
    UnitCost::UnitCost(UnitName u, std::string n, int m, int g, int t, int s, int sm)
        : un{u}, name{n}, min{m}, gas{g}, time{t}, sup{s}, sup_max{sm}
    { }

    std::vector<UnitCost> unit_costs {
        { Terran_SCV, "Terran SCV", 50, 0, 300, 1 },
        { Terran_Marine, "Terran Marine", 50, 0, 360, 1 },
	    { Terran_Firebat, "Terran Firebat", 50, 25, 360, 1 },
	    { Terran_Ghost, "Terran Ghost", 25, 75, 750, 1 },
	    { Terran_Medic, "Terran Medic", 50, 25, 450, 1 },
	    { Terran_Vulture, "Terran Vulture", 75, 0, 450, 2 },
	    { Terran_Goliath, "Terran Goliath", 100, 50, 600, 2 },
	    { Terran_Siege_Tank, "Terran Siege Tank", 150, 100, 750, 2 },
	    { Terran_Wraith, "Terran Wraith", 150, 100, 900, 2 },
	    { Terran_Dropship, "Terran Dropship", 100, 100, 750, 2 },
	    { Terran_Valkyrie, "Terran Valkyrie", 250, 125, 750, 3 },
	    { Terran_Science_Vessel, "Terran Science Vessel", 100, 225, 1200, 2 },
	    { Terran_Battlecruiser, "Terran Battlecruiser", 400, 300, 2000, 6 },
	    { Terran_Command_Center, "Terran Command Center", 400, 0, 1800, 0, 10 },
	    { Terran_Supply_Depot, "Terran Supply Depot", 100, 0, 600, 0, 8 },
	    { Terran_Refinery, "Terran Refinery", 100, 0, 600 },
	    { Terran_Barracks, "Terran Barracks", 150, 0, 1200 },
	    { Terran_Engineering_Bay, "Terran Engineering Bay", 125, 0, 900 },
	    { Terran_Missile_Turret, "Terran Missile Turret", 75, 0, 450 },
	    { Terran_Academy, "Terran Academy", 150, 0, 1200 },
	    { Terran_Bunker, "Terran Bunker", 100, 0, 450 },
	    { Terran_Factory, "Terran Factory", 200, 100, 1200 },
	    { Terran_Armory, "Terran Armory", 100, 50, 1200 },
	    { Terran_Science_Facility, "Terran Science Facility", 100, 150, 900 },
	    { Terran_Starport, "Terran Starport", 150, 100, 1050 },
	    { Terran_Machine_Shop, "Terran Machine Shop", 50, 50, 600 },
	    { Terran_Control_Tower, "Terran Control Tower", 50, 50, 600 },
	    { Terran_Comsat_Station, "Terran Comsat Station", 50, 50, 600 },
	    { Terran_Nuclear_Silo, "Terran Nuclear Silo", 100, 100, 1200 },
	    { Terran_Physics_Lab, "Terran Physics Lab", 50, 50, 600 },
	    { Terran_Covert_Ops, "Terran Covert Ops", 50, 50, 600 },
	    { Terran_Nuclear_Missile, "Terran Nuclear Missile", 200, 200, 1500, 8 },
	    { Terran_U238_Shells, "Terran U-238 Shells", 150, 150, 1500 },
	    { Terran_Stim_Pack, "Terran Stim Pack", 100, 100, 1200 },
	    { Terran_Restoration, "Terran Restoration", 100, 100, 1200 },
	    { Terran_Optical_Flare, "Terran Optical Flare", 100, 100, 1200 },
	    { Terran_Caduceus_Reactor, "Terran Caduceus Reactor", 150, 150, 2500 },
	    { Terran_Ion_Thrusters, "Terran Ion Thrusters", 100, 100, 1500 },
	    { Terran_Spider_Mines, "Terran Spider Mines", 100, 100, 1200 },
	    { Terran_Siege_Tech, "Terran Siege Tech", 150, 150, 1200 },
	    { Terran_Charon_Boosters, "Terran Charon Boosters", 100, 100, 2000 },
	    { Terran_Cloaking_Field, "Terran Cloaking Field", 150, 150, 1500 },
	    { Terran_Apollo_Reactor, "Terran Apollo Reactor", 200, 200, 2500 },
	    { Terran_EMP_Shockwave, "Terran EMP Shockwave", 200, 200, 1800 },
	    { Terran_Irradiate, "Terran Irradiate", 200, 200, 1200 },
	    { Terran_Titan_Reactor, "Terran Titan Reactor", 150, 150, 2500 },
	    { Terran_Lockdown, "Terran Lockdown", 200, 200, 1500 },
	    { Terran_Personnel_Cloaking, "Terran Personnel Cloaking", 100, 100, 1200 },
	    { Terran_Ocular_Implants, "Terran Ocular Implants", 100, 100, 2500 },
	    { Terran_Moebius_Reactor, "Terran Moebius Reactor", 150, 150, 2500 },
	    { Terran_Yamato_Gun, "Terran Yamato Gun", 100, 100, 1800 },
	    { Terran_Colossus_Reactor, "Terran Colossus Reactor", 150, 150, 2500 },
	    { Terran_Infantry_Weapons_1, "Terran Infantry Weapons 1", 100, 100, 4000 },
	    { Terran_Infantry_Weapons_2, "Terran Infantry Weapons 2", 175, 175, 4480 },
	    { Terran_Infantry_Weapons_3, "Terran Infantry Weapons 3", 250, 250, 4960 },
	    { Terran_Infantry_Armor_1, "Terran Infantry Armor 1", 100, 100, 4000 },
	    { Terran_Infantry_Armor_2, "Terran Infantry Armor 2", 175, 175, 4480 },
	    { Terran_Infantry_Armor_3, "Terran Infantry Armor 3", 250, 250, 4960 },
	    { Terran_Vehicle_Weapons_1, "Terran Vehicle Weapons 1", 100, 100, 4000 },
	    { Terran_Vehicle_Weapons_2, "Terran Vehicle Weapons 2", 175, 175, 4480 },
	    { Terran_Vehicle_Weapons_3, "Terran Vehicle Weapons 3", 250, 250, 4960 },
	    { Terran_Vehicle_Plating_1, "Terran Vehicle Plating 1", 100, 100, 4000 },
	    { Terran_Vehicle_Plating_2, "Terran Vehicle Plating 2", 175, 175, 4480 },
	    { Terran_Vehicle_Plating_3, "Terran Vehicle Plating 3", 250, 250, 4960 },
	    { Terran_Ship_Weapons_1, "Terran Ship Weapons 1", 100, 100, 4000 },
	    { Terran_Ship_Weapons_2, "Terran Ship Weapons 2", 175, 175, 4480 },
	    { Terran_Ship_Weapons_3, "Terran Ship Weapons 3", 250, 250, 4960 },
	    { Terran_Ship_Plating_1, "Terran Ship Plating 1", 100, 100, 4000 },
	    { Terran_Ship_Plating_2, "Terran Ship Plating 2", 175, 175, 4480 },
	    { Terran_Ship_Plating_3, "Terran Ship Plating 3", 250, 250, 4960 }
    };

    std::map <UnitName, UnitName> unit_builder {
        { Terran_SCV, Terran_Command_Center },
        { Terran_Marine, Terran_Barracks },
        { Terran_Firebat, Terran_Barracks },
        { Terran_Ghost, Terran_Barracks },
        { Terran_Medic, Terran_Barracks },
        { Terran_Vulture, Terran_Factory },
        { Terran_Goliath, Terran_Factory },
        { Terran_Siege_Tank, Terran_Factory },
        { Terran_Wraith, Terran_Starport },
        { Terran_Dropship, Terran_Starport },
        { Terran_Valkyrie, Terran_Starport },
        { Terran_Science_Vessel, Terran_Starport },
        { Terran_Battlecruiser, Terran_Starport },
        { Terran_Command_Center, Terran_SCV },
        { Terran_Supply_Depot, Terran_SCV },
        { Terran_Refinery, Terran_SCV },
        { Terran_Barracks, Terran_SCV },
        { Terran_Engineering_Bay, Terran_SCV },
        { Terran_Missile_Turret, Terran_SCV },
        { Terran_Academy, Terran_SCV },
        { Terran_Bunker, Terran_SCV },
        { Terran_Factory, Terran_SCV },
        { Terran_Armory, Terran_SCV },
        { Terran_Science_Facility, Terran_SCV },
        { Terran_Starport, Terran_SCV },
        { Terran_Machine_Shop, Terran_Factory },
        { Terran_Control_Tower, Terran_Starport },
        { Terran_Comsat_Station, Terran_Command_Center },
        { Terran_Nuclear_Silo, Terran_Command_Center },
        { Terran_Physics_Lab, Terran_Science_Facility },
        { Terran_Covert_Ops, Terran_Science_Facility },
        { Terran_Nuclear_Missile, Terran_Nuclear_Silo },
        { Terran_U238_Shells, Terran_Academy },
        { Terran_Stim_Pack, Terran_Academy },
        { Terran_Restoration, Terran_Academy },
        { Terran_Optical_Flare, Terran_Academy },
        { Terran_Caduceus_Reactor, Terran_Academy },
        { Terran_Ion_Thrusters, Terran_Machine_Shop },
        { Terran_Spider_Mines, Terran_Machine_Shop },
        { Terran_Siege_Tech, Terran_Machine_Shop },
        { Terran_Charon_Boosters, Terran_Machine_Shop },
        { Terran_Cloaking_Field, Terran_Control_Tower },
        { Terran_Apollo_Reactor, Terran_Control_Tower },
        { Terran_EMP_Shockwave, Terran_Science_Facility },
        { Terran_Irradiate, Terran_Science_Facility },
        { Terran_Titan_Reactor, Terran_Science_Facility },
        { Terran_Lockdown, Terran_Covert_Ops },
        { Terran_Personnel_Cloaking, Terran_Covert_Ops },
        { Terran_Ocular_Implants, Terran_Covert_Ops },
        { Terran_Moebius_Reactor, Terran_Covert_Ops },
        { Terran_Yamato_Gun, Terran_Physics_Lab },
        { Terran_Colossus_Reactor, Terran_Physics_Lab },
        { Terran_Infantry_Weapons_1, Terran_Engineering_Bay },
        { Terran_Infantry_Weapons_2, Terran_Engineering_Bay },
        { Terran_Infantry_Weapons_3, Terran_Engineering_Bay },
        { Terran_Infantry_Armor_1, Terran_Engineering_Bay },
        { Terran_Infantry_Armor_2, Terran_Engineering_Bay },
        { Terran_Infantry_Armor_3, Terran_Engineering_Bay },
        { Terran_Vehicle_Weapons_1, Terran_Armory },
        { Terran_Vehicle_Weapons_2, Terran_Armory },
        { Terran_Vehicle_Weapons_3, Terran_Armory },
        { Terran_Vehicle_Plating_1, Terran_Armory },
        { Terran_Vehicle_Plating_2, Terran_Armory },
        { Terran_Vehicle_Plating_3, Terran_Armory },
        { Terran_Ship_Weapons_1, Terran_Armory },
        { Terran_Ship_Weapons_2, Terran_Armory },
        { Terran_Ship_Weapons_3, Terran_Armory },
        { Terran_Ship_Plating_1, Terran_Armory },
        { Terran_Ship_Plating_2, Terran_Armory },
        { Terran_Ship_Plating_3, Terran_Armory }
    };

    std::multimap <UnitName, UnitName> unit_prereq {
        { Terran_SCV, Terran_Command_Center },
        { Terran_Marine, Terran_Barracks },
        { Terran_Firebat, Terran_Academy },
        { Terran_Ghost, Terran_Academy },
        { Terran_Ghost, Terran_Covert_Ops },
        { Terran_Medic, Terran_Academy },
        { Terran_Vulture, Terran_Factory },
        { Terran_Goliath, Terran_Armory },
        { Terran_Siege_Tank, Terran_Machine_Shop },
        { Terran_Wraith, Terran_Starport },
        { Terran_Dropship, Terran_Control_Tower },
        { Terran_Valkyrie, Terran_Armory },
        { Terran_Valkyrie, Terran_Control_Tower },
        { Terran_Science_Vessel, Terran_Science_Facility },
        { Terran_Science_Vessel, Terran_Control_Tower },
        { Terran_Battlecruiser, Terran_Physics_Lab },
        { Terran_Battlecruiser, Terran_Control_Tower },
        { Terran_Command_Center, Terran_SCV },
        { Terran_Supply_Depot, Terran_SCV },
        { Terran_Refinery, Terran_SCV },
        { Terran_Barracks, Terran_Command_Center },
        { Terran_Engineering_Bay, Terran_Command_Center },
        { Terran_Missile_Turret, Terran_Engineering_Bay },
        { Terran_Academy, Terran_Barracks },
        { Terran_Bunker, Terran_Barracks },
        { Terran_Factory, Terran_Barracks },
        { Terran_Armory, Terran_Factory },
        { Terran_Science_Facility, Terran_Starport },
        { Terran_Starport, Terran_Factory },
	    { Terran_Machine_Shop, Terran_Factory },
	    { Terran_Control_Tower, Terran_Starport },
	    { Terran_Comsat_Station, Terran_Academy },
	    { Terran_Nuclear_Silo, Terran_Covert_Ops },
	    { Terran_Physics_Lab, Terran_Science_Facility },
	    { Terran_Covert_Ops, Terran_Science_Facility },
	    { Terran_Nuclear_Missile, Terran_Covert_Ops },
	    { Terran_U238_Shells, Terran_Academy },
	    { Terran_Stim_Pack, Terran_Academy },
	    { Terran_Restoration, Terran_Academy },
	    { Terran_Optical_Flare, Terran_Academy },
	    { Terran_Caduceus_Reactor, Terran_Academy },
	    { Terran_Ion_Thrusters, Terran_Machine_Shop },
	    { Terran_Spider_Mines, Terran_Machine_Shop },
	    { Terran_Siege_Tech, Terran_Machine_Shop },
	    { Terran_Charon_Boosters, Terran_Machine_Shop },
	    { Terran_Cloaking_Field, Terran_Control_Tower },
	    { Terran_Apollo_Reactor, Terran_Control_Tower },
	    { Terran_EMP_Shockwave, Terran_Science_Facility },
	    { Terran_Irradiate, Terran_Science_Facility },
	    { Terran_Titan_Reactor, Terran_Science_Facility },
	    { Terran_Lockdown, Terran_Covert_Ops },
	    { Terran_Personnel_Cloaking, Terran_Covert_Ops },
	    { Terran_Ocular_Implants, Terran_Covert_Ops },
	    { Terran_Moebius_Reactor, Terran_Covert_Ops },
	    { Terran_Yamato_Gun, Terran_Physics_Lab },
	    { Terran_Colossus_Reactor, Terran_Physics_Lab },
	    { Terran_Infantry_Weapons_1, Terran_Engineering_Bay },
	    { Terran_Infantry_Weapons_2, Terran_Infantry_Weapons_1 },
	    { Terran_Infantry_Weapons_3, Terran_Infantry_Weapons_2 },
	    { Terran_Infantry_Armor_1, Terran_Engineering_Bay },
	    { Terran_Infantry_Armor_2, Terran_Infantry_Armor_1 },
	    { Terran_Infantry_Armor_3, Terran_Infantry_Armor_2 },
	    { Terran_Vehicle_Weapons_1, Terran_Armory },
	    { Terran_Vehicle_Weapons_2, Terran_Vehicle_Weapons_1 },
	    { Terran_Vehicle_Weapons_3, Terran_Vehicle_Weapons_2 },
	    { Terran_Vehicle_Plating_1, Terran_Armory },
	    { Terran_Vehicle_Plating_2, Terran_Vehicle_Plating_1 },
	    { Terran_Vehicle_Plating_3, Terran_Vehicle_Plating_2 },
	    { Terran_Ship_Weapons_1, Terran_Armory },
	    { Terran_Ship_Weapons_2, Terran_Ship_Weapons_1 },
	    { Terran_Ship_Weapons_3, Terran_Ship_Weapons_2 },
	    { Terran_Ship_Plating_1, Terran_Armory },
	    { Terran_Ship_Plating_2, Terran_Ship_Plating_1 },
	    { Terran_Ship_Plating_3, Terran_Ship_Plating_2 }
    };
}
}
